### ISSUE TITLE
License and Rights Statement metadata for Hyrax 2 upgrade

### ISSUE THREAD

**Issue by reliztrent** [gwu-libraries/scholarspace-hyrax#106]
Suggest replacing "All Rights Reserved" rights statement (which is a retired Europeana statement) with "In Copyright" http://rightsstatements.org/page/InC/1.0 statement

**Comment by reliztrent** [comment]
We should also consider using two Rights-related metadata fields:
1. License URL - a standardized statement from Creative Commons, RightsStatements.org, or another rights statement repository.
2. Rights - free text field for local or additional statements that don't have a URI/URL representing that statement.

**Comment by kerchner** [comment]
As per discussion on 18-June-2018:

- Both `license` and `rights_statement` will be required fields.
- Accept default Hyrax values
- For ingested items:  `rights` in the metadata JSON should be used to populate `license`
- For ingest_work:
    - If `rights` is `None` then set `license` to `All rights reserved`.  Else, accept the value as-is with no transformation.
    - Set `rights_statement` to `In Copyright`
- For ingest_etd:
    - Set `license` to `All rights reserved`
    - Set `rights_statement` to `In Copyright`

Alternative representation:


| LD/RDF | Sufia label | Hyrax label |   Migration - from GWSS | Migration - ETDs from ProQuest, and Hyrax 1 --> 2 upgrade |
|----|----|----|----|----|
| dc:rights | Rights | License |   From GWSS: If `None` --> `All rights reserved`, else migrate as-is | Set to `All rights reserved` |
| edm:rights | N/A | Rights Statement |  Set to `In Copyright` |  Set to `In Copyright` |
