### ISSUE TITLE
Facets - Use the same facet list for all work types

### ISSUE THREAD

**Issue by reliztrent** [gwu-libraries/scholarspace-hyrax#124]
Facets - Use the same facet list for all work types, but certain facets should have an indicator to the user that they don’t apply to the current material (like GW Unit for materials not produced by GW, such as Teamster magazines). 

This is a known usability problem for CONTENTdm repos, and we can learn from the mistakes of that platform.
 
CONTENTdm facets change when you look at different content types. If you look at 2+ content types at once (which usually happens whenever you search for content), yet another list of facets change. This was widely perceived as very confusing for users and a major usability issue that shouldn’t be introduced into other systems. Users couldn’t tell why the facets were changing with each search.

**Comment by kerchner** [comment]
If you use facets to narrow down to a subset of items which ALL do not have any values for a certain metadata field, then that facet will not show up.   For example, if you were to select facet values (for example, author) or use collections to narrow down to just Teamster magazines, and zero of those items have a value for GW Unit, then the GW Unit facet will not show up (in my experience with the Hyrax UI).

@reliztrent please try for yourself and determine whether this issue can be closed.

**Comment by kerchner** [comment]
Assigning to @reliztrent - see above comment.

**Comment by kerchner** [comment]
Closing this issue considering the behavior noted in the comment above, i.e. that once the user subsets, irrelevant facets are hidden.
