### ISSUE TITLE
Ability to search for terms in specific fields (Advanced Search)

### ISSUE THREAD

**Issue by reliztrent** [gwu-libraries/scholarspace-hyrax#127]
Currently, for example, users cannot search by the date field or title field.

**Comment by reliztrent** [comment]
Fields that should be searchable by field (and which are not currently facets):
- Title
- Series (IsPartOf)
- Date Created & Date Created free text
- Rights Statement
- License


Example searches that should be ca

**Comment by kerchner** [comment]
Ref. #125 re: Rights Statement and License as potential facets

**Comment by kilahimm** [comment]
https://github.com/projectblacklight/blacklight_advanced_search seems like a good place to start.

**Comment by kerchner** [comment]
Goal is to produce links to scoped results

**Comment by kerchner** [comment]
Implemented in #551
