### ISSUE TITLE
Difficult for users to find a way to access the PDF for items

### ISSUE THREAD

**Issue by reliztrent** [gwu-libraries/scholarspace-hyrax#133]
On item view page and file view pages on standard laptop screens, there are no links to the PDF "above the fold". Not tested with non-PDF items.

As a user, I would expect the following things to be links to the actual PDF:

## Item view page (e.g., https://scholarspace-etds.library.gwu.edu/concern/gw_etds/p2676v80j?locale=en)

**Doesn't link as expected**

- Thumbnail at top of page (not a link)
- Thumbnail at bottom of page (links to the file view page)
- Title at bottom of page (links to the file view page)

**Does link as expected** 

- "Download PDF" link below the thumbnail 

## File view page  (e.g., https://scholarspace-etds.library.gwu.edu/concern/parent/p2676v80j/file_sets/8g84mm437)

**Doesn't link as expected**

- Title at the top of the page (not a link)
- Thumbnail at the top of the page (not a link)

**Does link as expected** 

- "Download PDF" button below thumbnail

**Comment by kerchner** [comment]
The "Download PDF" button is prominent and clear.  It does exactly what it says.
