### ISSUE TITLE
Create metadata reference for batch-loader

### ISSUE THREAD

**Issue by reliztrent** [gwu-libraries/scholarspace-hyrax#154]
The CSV

- column names, and
- values, in the case of "controlled vocabulary" fields such as resource_type
- will need to match the metadata "short names" in GWSS (e.g. title, description, etc.).

This task is to create a reference to be used in creating the CSV for batch-loader.

**Comment by kerchner** [comment]
Resolved in https://github.com/gwu-libraries/batch-loader/commit/2206b19592b8976c592751cf273551da9abf02f5#diff-04c6e90faac2675aa89e2176d2eec7d8
