### ISSUE TITLE
Use AvenirLTStd-Roman font

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace-hyrax#168]
Note that ISIS Files has been able to use GW styling, with this font.

**Comment by kerchner** [comment]
@maxturer Can we close this ticket in light of the Hyrax 2.0 UI refresh - are we GW-compliant with the font now being used in GW ScholarSpace 2.0?

**Comment by maxturer** [comment]
@kerchner We can! We are now using Gibson and are even more GW-compliant.
