### ISSUE TITLE
GWSS not uploading files

### ISSUE THREAD

**Issue by rareleah** [gwu-libraries/scholarspace-hyrax#183]
Hello,
Schol Commies have encountered an issue attaching files to records. We've been able to create a record and attempt to upload the file but when we save the file doesn't upload. Matt looked at the logs but wasn't able to resolve the issue.
Two examples of records where we've encountered this issue:
https://scholarspace.library.gwu.edu/concern/gw_works/76537174s?locale=en 

https://scholarspace.library.gwu.edu/concern/gw_works/rx913q26p?locale=en 

Thank you!

**Comment by reliztrent** [comment]
Zip, png, txt, and tif files upload successfully.

Tested ~ 12 different PDFs from different projects/contexts, some with OCR and some without. None of the 12 PDFs uploaded successfully. All tested on item https://gwscholarspace-test2.wrlc.org/concern/gw_works/x346d4610

**Comment by kerchner** [comment]
Resolved.  An update to ImageMagick (the apt-managed package) seemed to have changed the policy configuration that allows for reading PDF files.  Noted in this repo's wiki page on application troubleshooting.
