### ISSUE TITLE
Bibliographic Citation attribute not accepting values for new objects & needs to display on work view

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace-hyrax#194]
Suggested solution: Add `:bibliographic_citation` to `_attribute_rows.rb`

**Comment by reliztrent** [comment]
Also suggest replacing "Previous Publication Information" display language with "Citation" or other label that more broadly matches intended use of this field (qdc:bibliographicCitation - http://dublincore.org/documents/dcmi-terms/#terms-bibliographicCitation)

**Comment by reliztrent** [comment]
Uses cases include: 
ETDs
Monographs
Archival folders  (e.g.: Collection number.Collection name, Series number.Series name, Subseries number.Subseries name, Box number, Folder number)
Archival items (e.g.: Collection number.Collection name, Series number.Series name, Subseries number.Subseries name, Box number, Folder number, Item number or name)
Serials, bibliographic
Serials, archival
Datasets

**Comment by dolsysmith** [comment]
I added a work this morning and tried to use this field, and it doesn't even save the data I enter, much less display it. In other words, I enter the text in the field and click save, but when I return to the edit view, the field is empty again.

Here's the work: https://scholarspace.library.gwu.edu/concern/gw_works/qv33rx376?locale=en

**Comment by kerchner** [comment]
This may have been resolved by https://github.com/gwu-libraries/scholarspace-hyrax/commit/039fef2305d0841471eb7020067e7a2f16377269 - verify after merging in t158-hyrax-2.4.1 branch

**Comment by kerchner** [comment]
The commit ref'd above is not in Hyrax 2.4.1.

Ref. conversation on https://github.com/samvera/hyrax/pull/2834

There seems to be some discussion as to how this field is being used by various Hyrax adopters.
@reliztrent one suggestion that seems (I think??) in line with how we are trying to use it that a field based on `dcterms:source` as you've suggested in #198 would be more appropriate -- I believe we're trying to cite the original work that this GWSS work came from.

While I _can_ patch with 039fef2 to get the field to show, I'd like to first understand:
- What is the way we use this field?
- What is the way we would like to use `dcterms:source` as per #198 ?

**Comment by reliztrent** [comment]
See https://docs.google.com/document/d/1tiy3xWpZJFFJGqQyIxNVGQ2SrNGgtIMrUqZMp_Aj_hM/edit

**Comment by dolsysmith** [comment]
Is there any update on this feature fix? ScholComm has a need for this field to ensure that we are in compliance with publisher agreements that require indicating the version of record when hosting pre and post prints in an institutional repository.

**Comment by kerchner** [comment]
maintain as free text
