### ISSUE TITLE
Change "Share your work" button URL

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/scholarspace-hyrax#197]
Change URL to: https://docs.google.com/forms/d/e/1FAIpQLSfasnzb2NjLsw7YRBvEJcw1GCfSsY6DVqvF3sdKlWs2uvEP2w/viewform?usp=sf_link

**Comment by kerchner** [comment]
@kilahimm Does this still need to be changed?  It appears that http://library.gwu.edu/scholarspace/submit is redirecting to the Google Form URL.  Is the redirect just a temporary workaround, and the desire is to be able to remove the redirect?

**Comment by kilahimm** [comment]
@kerchner from what I understand the webteam would like to deprecate that page which would require  a change inside of Scholarspace.
