### ISSUE TITLE
Add Dublin Core "Source" field

### ISSUE THREAD

**Issue by reliztrent** [gwu-libraries/scholarspace-hyrax#198]

**Comment by kerchner** [comment]
Add `dcterms:source`

**Comment by kerchner** [comment]
Note that `bibliographic_citation` is from the Dublin Core vocabulary.  See https://github.com/samvera/hyrax/blob/v2.5.0/app/models/concerns/hyrax/basic_metadata.rb#L31  
```
property :bibliographic_citation, predicate: ::RDF::Vocab::DC.bibliographicCitation
```
This line is the same in previous Hyrax tags as well.  Closing issue.
