### ISSUE TITLE
Update About and Help text

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace-hyrax#21]
Base on https://scholarspace.library.gwu.edu/help and https://scholarspace.library.gwu.edu/about

**Comment by kerchner** [comment]
@reliztrent please work with Beth and Valerie

**Comment by reliztrent** [comment]
Determination of new language completed. 

**About:** Leave text the same as ScholarSpace, with added comment in a Bootstrap alert that reads "Ftsor information about uploading your Electronic Thesis or Dissertation, please see http://library.gwu.edu/etd"

**Help:** Leave text as-is. No edits.

**Comment by kerchner** [comment]
If we're going to do this via the default TinyMCE tool, there appears to be an issue w/Hyrax whereby it's ignoring `config/tinymce.yml`.

This method of initializing TinyMCE
https://github.com/samvera/hyrax/blob/081761217afe434c983cc374b31c925e3d8ec1dd/app/assets/javascripts/hyrax/app.js#L26-L28
would seem to be more of a "manual initialization" as per https://github.com/spohlenz/tinymce-rails

Options:
(1) Convert about and help into static pages
(2) Override the Hyrax pages with correct TinyMCE initialization (and submit a ticket to Hyrax)
(3) Upload these pages as text and configure in the default tool.

**Comment by kerchner** [comment]
Adding the HTML as code via the TinyMCE control is going to require configuring TinyMCE to add the "code" button.  Currently, the configuration in tinymce.yml seems to be ignored in Hyrax - this will need to be resolved.

**Comment by kerchner** [comment]
Posted question to samvera-tech list:  see https://groups.google.com/forum/#!topic/samvera-tech/gAXLum3EFGI

**Comment by kerchner** [comment]
See response in thread, referencing https://github.com/uclibs/scholar_uc/pull/1763/ .

The thread resulted in the creation of this Hyrax ticket: https://github.com/samvera/hyrax/issues/2273

**Comment by kerchner** [comment]
Paste these into About and Help via edit button:

About page: https://gist.github.com/kerchner/ed8e511d209dcc47dd8a814033804326
Help page: https://gist.github.com/kerchner/98e0809ef8b023450911925c68dce4f6
