### ISSUE TITLE
Allow works to be viewed in browser rather than download only

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/scholarspace-hyrax#217]
See: https://github.com/samvera/hyrax/issues/3149

**Comment by kilahimm** [comment]
@kerchner is it possible to test patching downloads_controller.rb to allow for inline rendering as opposed to downloads of attachments?
https://github.com/samvera/hyrax/blob/v2.5.1/app/controllers/hyrax/downloads_controller.rb

ie:
```
# Override the Hydra::Controller::DownloadBehavior#content_options so that
# we have an attachement rather than 'inline'
  def content_options
    super.merge(disposition: 'inline')
   end
```

I've received another request to bring back this functionality.

**Comment by kerchner** [comment]
As per discussion:
- Context is for images in https://scholarspace.library.gwu.edu/collections/kd17ct46z
- Let's try addressing this via IIIF #204

**Comment by kerchner** [comment]
Consider perhaps an alternate route/link per item that allows user to view in browser.  And/or a "View in browser" or click on the thumbnail, per landing page
