### ISSUE TITLE
Export task for DC metadata

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/scholarspace-hyrax#220]
Investigate best practice for export Dublin Core metadata to third party systems.  Use case is to make GWSS content searchable in Primo.  Some options are exporting DC metadata as XML or creating an OAI feed that can be harvested.

**Comment by kerchner** [comment]
We should first do #274

**Comment by dolsysmith** [comment]
See documentation on Primo VE [import profiles](https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/020Primo_VE/Primo_VE_(English)/100Loading_Records_from_External_Sources_into_Primo_VE/Configuring_Import_Profiles_for_Primo_VE) for external metadata sources.

**Comment by dolsysmith** [comment]
- Use basic DC schema (as implemented by Blacklight/Blacklight-OAI gems) for Primo VE import.
-  GWSS modifications (to `SolrDocument` class):
   - `dc:identifier` field should contain GWSS ID (for creating the link in Primo)
   - `dc:contributor` field should be structured as follows, to ensure proper hyperlinking of names in Primo:
   ```
   <dc:contributor>Lastname, FirstName, advisor.$$QLastName, FirstName</dc:contributor>
   ```
