### ISSUE TITLE
Improve handling of DOIs

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/scholarspace-hyrax#221]
Investigate handling of DOIs as identifiers in GWSS.  See https://scholar.uc.edu/concern/articles/wp988k10f?locale=en

One issue with the existing implementation is that the Identifier field used performs a faceted search when it's clicked on rather than linking out to the DOI url.

**Comment by dolsysmith** [comment]
In the Hyrax FAQ's, there is this note: "Hyrax does not yet provide DOI integration, but there is a hydra-remote-identifier gem that is intended to be implemented atop Hyrax in your application and there are Hyrax installations that have already done this and may be consulted."

**Comment by kerchner** [comment]
This functionality appears to now be built into Hyrax 2.9.0 (and Hyrax 3).  We are currently on 2.8.0.   See https://github.com/samvera/hyrax/pull/4465 (which is a backport of https://github.com/samvera/hyrax/pull/4458).  Work on this ticket might start with finding Hyrax 2.9.0 (or Hyrax 3) implementations which use this capability.

**Comment by cjcolvar** [comment]
I've been working on a Hyrax plugin which provides DOI support and would be really interested in your feedback and use cases.
https://github.com/ubiquitypress/hyrax-doi
I'll be cutting a 0.2.0 release soon and probably moving it over to samvera-labs in github.

**Comment by kerchner** [comment]
Thanks @cjcolvar, this is great to know.  We will be working on our upgrade to Hyrax 2.9.0 within the upcoming weeks, so that should afford us the ability to try the `hyrax-doi` gem.  Looking forward to trying it and providing feedback.

**Comment by kerchner** [comment]
We are not looking to mint DOIs, so we would not necessarily need the gem referenced above.  For us, this can be implemented as:

- Create a new DOI metadata field that is a URL.  Multiple values allowed.
- Create a separate ticket to migrate Identifier values on existing works which match DOI pattern; migrate these to the new DOI field
- Identifier should NOT be a faceted link.

**Comment by kerchner** [comment]
Issue to migrate identifier values to new DOI field is #274

**Comment by kerchner** [comment]
Need decisions on:
- Where should DOI render in the order of metadata fields?
- Update to `Identifier` field help text.  Currently says: `A unique handle identifying the work. An example would be a DOI for a journal article, or an ISBN or OCLC number for a book.`
