### ISSUE TITLE
Add new work type: Journal Issue

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/scholarspace-hyrax#223]
Journal work types require unique metadata that the GwWork type does not support well.  It would be worth exploring adding a work type for this kind of content.

**Comment by kerchner** [comment]
- Volume
- Issue

Look at using Collections to show the Journal/Publication.   How does it appear on the Work page? 

Hence, the work type would be "Journal Issue" and Collection type would be "Journal"

Also need to convert existing works into the new type - reach out to ScholComm to identify these items

There are also articles that are part of issues.   Consider works and child works.  Maybe work types are:
- Journal Issue
- Journal Article (should be same metadata as GwWork)

Most critical is Journal Issue work type.  Metadata would be:
- Volume (non-mandatory)
- Issue (non-mandatory)
