### ISSUE TITLE
Reimplement Terms of Use from OGC

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/scholarspace-hyrax#249]
The terms of use appears to have reverted to the default Hyrax terms.

https://docs.google.com/document/d/1jxWhZ3qaSHYOZdnEIyaWpx9nT6l8k1nNdPZeobndxU8/edit

**Comment by kerchner** [comment]
Reopening to verify that the commit above worked.

**Comment by kerchner** [comment]
Confirmed.
