### ISSUE TITLE
Updates to License display labels

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace-hyrax#266]
Current labels:
```
    - id: http://creativecommons.org/licenses/by/3.0/us/
      term: Attribution 3.0 United States
      active: true
    - id: http://creativecommons.org/licenses/by-sa/3.0/us/
      term: Attribution-ShareAlike 3.0 United States
      active: true
    - id: http://creativecommons.org/licenses/by-nc/3.0/us/
      term: Attribution-NonCommercial 3.0 United States
      active: true
    - id: http://creativecommons.org/licenses/by-nd/3.0/us/
      term: Attribution-NoDerivs 3.0 United States
      active: true
    - id: http://creativecommons.org/licenses/by-nc-nd/3.0/us/
      term: Attribution-NonCommercial-NoDerivs 3.0 United States
      active: true
    - id: http://creativecommons.org/licenses/by-nc-sa/3.0/us/
      term: Attribution-NonCommercial-ShareAlike 3.0 United States
      active: true
    - id: http://creativecommons.org/publicdomain/mark/1.0/
      term: Public Domain Mark 1.0
      active: true
    - id: http://creativecommons.org/publicdomain/zero/1.0/
      term: CC0 1.0 Universal
      active: true
    - id: http://www.europeana.eu/portal/rights/rr-r.html
      term: All rights reserved
      active: true
```

Will update with new labels.

**Comment by kilahimm** [comment]
Request to add CC licenses without a version number which link back to the https://creativecommons.org/licenses/ page

Ie:
```
    - id: http://creativecommons.org/licenses
      term: Attribution-NonCommercial-NoDerivs
      active: true
```

This was discussed at ScholComm stakeholder meeting.

**Comment by kerchner** [comment]
@kilahimm I would propose the following specifics:
- Add new version-less CC licenses
- Deactivate versioned CC licenses so they no longer show up as options to select.  This will not change any values for existing items (but see next item)
- Do we wish to change the licenses on existing items with versioned CC licenses?  If not, then no action to be taken.  If so, then there will be a task to migrate existing items.

We also need to clarify what the new items' labels (`id` above) and display values (`term` above) will be.  `id` values must be unique, as these are the values that are stored with the item metadata, so giving them all `id` of `http://creativecommons.org/licenses` will not work with the application as-is.

**Comment by kerchner** [comment]
Proposed scope of work: deactivate 3.0 CC licenses, add 4.0

**Comment by kerchner** [comment]
Leave all versions active.  We may need to deposit items that were created under 2.0, 3.0, etc.

Task here is to add 4.0 licenses, don't deactivate anything.
