### ISSUE TITLE
Add missing CC licenses

### ISSUE THREAD

**Issue by dolsysmith** [gwu-libraries/scholarspace-hyrax#272]
We currently only have CC 3.0, but CC 2.0 and 4.0 are both in use. We need to add these so we can cover all the license types. Should link back to the Creative Commons license pages (as for the CC license versions already in use).

**Comment by kerchner** [comment]
@dolsysmith Have you seen #266?

**Comment by dolsysmith** [comment]
@kerchner Sorry, I submitted that one for Barrett on behalf of Schol Comm; I don't think he understood that you had already created a ticket. I shared #266 with him so that he can see the specifics.

**Comment by kerchner** [comment]
Resolved along with #266 in PR #275
