### ISSUE TITLE
Migrate identifier values on existing works to DOI field 

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace-hyrax#274]
Where identifier values match DOI pattern, migrate value to new DOI field created in #221.

**Comment by dolsysmith** [comment]
The script used by the Jekyll journal sites for retrieving search results from GWSS's Solr index requires the DOI as a matchpoint; for those journal articles in GWSS, the DOI is in the "related_url" field. Would it be possible to test this change in gwscholarspace-test2 before it moves to prod? 

I imagine I'll just need to update the reference to the field in the Jekyll site code, but I'd like to make sure before it hits production. Alternately, if it would be possible just to copy the DOI into the new field instead of removing it from the old field, that would work (and wouldn't require me to make any changes to the code on my end).

**Comment by kerchner** [comment]
Definitely, part of the work of this ticket shall now include testing the update with the script used by the Jekyll sites.

**Comment by kerchner** [comment]
I would prefer moving, not copying, the value, to avoid redundant metadata values on these works.

**Comment by kerchner** [comment]
Perhaps we can accomplish this as a Bulkrax import to update existing items' metatdata

**Comment by dolsysmith** [comment]
I think the following should do the trick, which could be run as a script with the `rails runner` command:

```
data = ActiveFedora::SolrService.query("related_url_tesim:https://doi*", rows: 10000)
ids = data.map {|d| d.id}
ids.each do |id|
	work = GwWork.find(id)
	doi = work.related_url
	work.doi = doi
	work.related_url = []
	work.save
end

```

**Comment by kerchner** [comment]
@dolsysmith This looks good, but if you haven't done it already, I would do a "dry run" first to inspect the list of all `related_url` values.  It is possible that some works have `related_url` values which would not be suitable as `doi` values; we might want to leave those as-is.

**Comment by dolsysmith** [comment]
@kerchner Is it possible to do a test run on scholarspace-test2 first? I think you mentioned the test server wasn't working...

**Comment by kerchner** [comment]
I think I had my servers confused, it's working.   What I would recommend is to point your dev server's fedora/solr yml files to the URLs for production, and do the read-only operation to get the data.

**Comment by dolsysmith** [comment]
Ran the script on the test server and can confirm that 308 works were affected. (Prior to making the update, I tested with a pysolr query to verify that none of these works had multiple URL's in the `related_url` field.) Before running in production, I will test updating the logic on the Jekyll sites.

**Comment by dolsysmith** [comment]
Test journal sites are working after updating the Solr field name. Ready for deployment.

**Comment by dolsysmith** [comment]
@kerchner I isolated only those values that start with the string `https://doi`, so yes, I think it's safe to say so.

**Comment by kerchner** [comment]
Sounds like it's safe to proceed, then.

**Comment by kerchner** [comment]
@dolsysmith Thanks also for the script code above.  Would you like to add a page on the wiki where this script can be posted as an example of one way to migrate metadata values?  There are a couple of other metadata cleanup items that this might be handy for.  (One example that comes to mind is a value of GW_Unit that needs to be updated in a few cases)
