### ISSUE TITLE
Log Level :debug in production.rb

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/scholarspace-hyrax#281]
The environments/production.rb file on the server has been getting overwritten during new deployments.  The environments/production.rb.template file in the repo was made from environments/developnment.rb.

We should pull a environments/production.rb file from a clean install of Hyrax or ISIS Files so that we are working from a template that is based off a production deployment and not development.

**Comment by kerchner** [comment]
@kilahimm there is no environments/production.rb file in the repository, so there isn't anything about the deployment process that would overwrite it, that I am aware of.  However, it does look like the production.rb.template file does need to be updated.
