### ISSUE TITLE
Evaluate replacing ScholComm bulk loader with Bulkrax 

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace-hyrax#299]
Note that files will still have to be on the server and/or on OneDrive

**Comment by kerchner** [comment]
The above is no longer true.  Bulkrax allows uploads of a zip file through the UI.  Large-ish zip files (for example, 50+ works with 100+ files) seem to work fine, so far.

@dolsysmith Do you concur that Bulkrax will be the tool for non-ETD bulk uploads going forward?  If so, we can close this ticket.

**Comment by dolsysmith** [comment]
@kerchner I think so. As you mentioned, we may run into issues uploading very large batches of files in the UI, but that doesn't occur very often.

**Comment by kerchner** [comment]
@dolsysmith A workaround in that scenario would be to break the upload into smaller batches (each with its respective rows from the original CSV).

Closing this issue.
