### ISSUE TITLE
Update migration tasks

### ISSUE THREAD

**Issue by dolsysmith** [gwu-libraries/scholarspace-hyrax#301]
A release number is now required to inherit from `ActiveRecord::Migration`.  See the files in `db/migrate` in the [ISIS files repo](https://github.com/gwu-libraries/isisfiles-hyrax/tree/master/db/migrate). Copying the files from that repo into `scholarspace-hyrax/db/migrate` seems to work.

**Comment by kerchner** [comment]
These were included in https://github.com/gwu-libraries/scholarspace-hyrax/commit/26e082ccffffe389e377005aba36ff4af44cece4 .  @dolsysmith confirming that this issue can now be closed?

**Comment by dolsysmith** [comment]
Yes, closing now.
