### ISSUE TITLE
Hyrax 2 --> 3.x upgrade

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace-hyrax#313]

**Comment by kerchner** [comment]
Proposed plan is:
- Upgrade to 3.0.0 (see upgrade instructions https://github.com/samvera/hyrax/releases/tag/v3.0.0)
- Regression test (@alepbloyd and @kerchner )
- After reviewing release notes for releases > 3.0.0 and < 3.5.0 to determine if intermediate upgrades would be prudent, upgrade to 3.5.0.
- Regression test (@alepbloyd and @kerchner )
Github views such as https://github.com/samvera/hyrax/compare/v3.0.0...hyrax-v3.5.0 may be helpful in comparing code changes between releases, to look for changes in any files that our app overrides.

**Comment by kilahimm** [comment]
Resolved in #401
