### ISSUE TITLE
Improve banner image

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace-hyrax#32]
The current banner image (accessible at https://gist.github.com/kerchner/96b8863e2eeb8900e798f0a7974fb3fb ) does not render particularly well in the context of the unmodified Hyrax-based ScholarSpace ETDs page.

While we can improve styling after deployment, the current goal is to address only critical items before deployment.  However, we do at least want a banner image that will render well in context.  The attached zip file should provide a complete static version of the web page, for context:
[GWSSHomePage.zip](https://github.com/gwu-libraries/scholarspace-hyrax/files/1297124/GWSSHomePage.zip)
 
As per https://github.com/gwu-libraries/scholarspace-hyrax/blob/master/config/initializers/hyrax.rb#L110 , the banner image should be 5000px by 1000px.

**Comment by maxstarkenburg** [comment]
There is some CSS:
```
.image-masthead .background-container {
    ... 
    -webkit-filter: blur(1px);
    filter: blur(1px);
}
```
that is causing the blurriness. However, it also appears that the image doesn't look great at certain browser sizes / resolutions (the words don't always appear in the visible space, for example). Let me work on an image that will hopefully be better in those respects.

**Comment by kerchner** [comment]
@maxstarkenburg If you like, we should be able to override the stylesheet that's adding the `filter:blur` (I believe it's coming from this layer --> https://github.com/samvera/hyrax/blob/v1.0.4/app/assets/stylesheets/hyrax/_home-page.scss ).  I'll give that a try so we can have the option of more control.

**Comment by maxstarkenburg** [comment]
I think this one should work better.

![etds-22](https://user-images.githubusercontent.com/3514521/30391694-60501030-9888-11e7-8e13-5e75a2b21318.jpg)

**Comment by kerchner** [comment]
As per above, `filter: blur(1px);` should be overridden to be `filter: none;`.  So far, this has proven challenging to override in the files in `app/assets/stylesheets` (and/or the `hyrax` subdirectory) - but the solution lies somewhere there.
