### ISSUE TITLE
Improve sidekiq deployment around rake secret

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace-hyrax#320]
Is there a way to set this up so that `SECRET_KEY_BASE` doesn't have to be set in multiple places?  Without setting it in `sidekiq.service`, sidekiq couldn't start, in _some_ deployments.  Our other Hyrax application works without setting it in `sidekiq.service`.

**Comment by kerchner** [comment]
Now that we're using the `dotenv-rails` gem (see https://github.com/gwu-libraries/scholarspace-hyrax/commit/637d22dcd8812d6afbb9f0443fc211ea9e896add), this should be easier to set in `.env`

**Comment by dolsysmith** [comment]
No longer applicable in Docker deployment.
