### ISSUE TITLE
Comply with Google Scholar indexing requirements

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace-hyrax#343]
Ref: https://github.com/curationexperts/schoolie

Ref: #123 
Ref: [#189](https://github.com/gwu-libraries/scholarspace/issues/189) (from "old scholarspace")

**Comment by DaltonAlves** [comment]
- Users expect works uploaded to GWSS to be crawled by Google Scholar
    - https://www.youtube.com/watch?v=ucp6p-skEwE 
        - Presentation by Emory about use of Schoolie in 2022 to get GScholar to index. Claimed it worked within 1 day of pushing to production
    - Apparently, google scholar doesn’t like mixed repositories (scholarly + cultural heritage content). Might need to manage meta tags by item types to sort between scholarly and cultural heritage content? include: (just set up meta tags for ETDs, article, journal, poster, research paper, book review, reports,...) and exclude others (archival materials, others, microfilm,...)
    - May need to think through mapping of DublinCore elements to meta tags, see configuring meta notes: https://scholar.google.com/intl/en/scholar/inclusion.html
    - Don’t quite understand the implications with the sitemaps



User Stories:
As a faculty member, I want my research material deposited in GWSS to be discoverable via Google Scholar

As a researcher, I want to find scholarly information hosted by GWSS when searching Google Scholar

As repository manager, I want to ensure that only scholarly works are indexed by google scholar (not cultural heritage items).

**Comment by kerchner** [comment]
Some observations about sitemap content:

One of the factors mentioned in the Schoolie youtube video is "last modified" dates in the sitemap.  Our current sitemap entries look like this:
```
<url>
  <loc>https://scholarspace.library.gwu.edu/concern/gw_works/kp78gg623</loc>
  <priority>1</priority>
  <changefreq>weekly</changefreq>
</url>
```
whereas the Emory ETD repository has entries that look like this:
```
<url>
  <loc>https://etd.library.emory.edu/concern/etds/qr46r240n</loc>
  <lastmod>2024-01-16T20:58:57Z</lastmod>
</url>
```
Emory's repository does not use a sitemap generator gem; rather, they have custom code to create the sitemap, like this:  https://github.com/curationexperts/laevigata/blob/main/lib/tasks/schoolie.rake

**Comment by kerchner** [comment]
Based on https://scholar.google.com/intl/en/scholar/inclusion.html#indexing it appears we may need to vary the meta tags provided based on the type of work (and even within GwWork) -- do we need to key on `resource_type`?

## ETDs

(I think we are okay for GwEtd works here as long as we use `schoolie` the same way that Emory does) 

_For theses, dissertations, and technical reports, provide the remaining bibliographic citation data in the following tags: citation_dissertation_institution, citation_technical_report_institution or DC.publisher for the name of the institution and citation_technical_report_number for the number of the technical report. As with journal and conference papers, you need to provide sufficient information to recognize a formal citation to this document from another article._

## Journal and Conference papers

_For journal and conference papers, provide the remaining bibliographic citation data in the following tags: citation_journal_title or citation_conference_title, citation_issn, citation_isbn, citation_volume, citation_issue, citation_firstpage, and citation_lastpage. Dublin Core equivalents are DC.relation.ispartof for journal and conference titles and the non-standard tags DC.citation.volume, DC.citation.issue, DC.citation.spage (start page), and DC.citation.epage (end page) for the remaining fields. Regardless of the scheme chosen, these fields must contain sufficient information to identify a reference to this paper from another document, which is normally all of: (a) journal or conference name, (b) volume and issue numbers, if applicable, and (c) the number of the first page of the paper in the volume (or issue) in question._

## Other works?

Are there other work types (`resource_type`) which we do NOT want indexed in Google Scholar, if they are not scholarly works as defined by Google Scholar?
