### ISSUE TITLE
Regression on in browser view of PDFS

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/scholarspace-hyrax#367]
See previous issue #217 which had implemented downloading PDfs in the browser rather than to the local machine.

**Comment by kerchner** [comment]
@kilahimm is the issue that this is no longer working?

**Comment by alepbloyd** [comment]
Would we potentially want to have an option for downloading and an option for opening in browser if preferences are split? Was able to get this working in my local dev environment with a button for each. 

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/17027357/217092979-df6fdd98-6987-4b0f-9f80-3d01a55f7382.png">
