### ISSUE TITLE
Investigate changes to Google Analytics

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/scholarspace-hyrax#369]
Google analytics is moving to V4 starting in July.  Need to confirm whether anything needs to changes in Hyrax code.

**Comment by kerchner** [comment]
Use 3.6.0 based Hyrax (#384) and configure and test Google Analytics with our GA code

**Comment by kerchner** [comment]
#83 can be closed when this is closed.

**Comment by dolsysmith** [comment]
GA4 configured and working now.
