### ISSUE TITLE
Update Blacklight YML template 

### ISSUE THREAD

**Issue by dolsysmith** [gwu-libraries/scholarspace-hyrax#378]
`config/blacklight.yml.template` refers to the Solr core for production as `blacklight-core`. In production, the core is actually named `scholarspace`, and that name is reflected in `blacklight.yml`, but neither in the template nor in the documentation.

**Comment by dolsysmith** [comment]
In the Dockerized version, I am putting the name of the core in a .env file.

**Comment by kilahimm** [comment]
Resolved in #401
