### ISSUE TITLE
Fix Imagemagick7 link to more persistent link

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace-hyrax#380]
In https://github.com/gwu-libraries/scholarspace-hyrax/blob/5d0afcf2e538e6c61990f254f34375b5cb556c68/Dockerfile#L12
link to https://imagemagick.org/archive/releases/ instead, for wget.

**Comment by kerchner** [comment]
Fixed in [24c97b7](https://github.com/gwu-libraries/scholarspace-hyrax/commit/24c97b736e3c805bdbd20fde7a501a94a7d3e74d)

**Comment by kilahimm** [comment]
Resolved in #401
