### ISSUE TITLE
Test and configure ETD Loader and Bulkrax

### ISSUE THREAD

**Issue by alepbloyd** [gwu-libraries/scholarspace-hyrax#386]
Current status:
- Using `python etd_loader.py --only retrieve`, able to retrieve files from ETD ftp server on local development instance using python v `3.6.15`
- Working on updating code to utilize Bulkrax for the import process rather than current custom code.

**Comment by kerchner** [comment]
Closed by implementation of Bulkrax ETD loader in #555
