### ISSUE TITLE
Summer 2023 UI Enhancements Hyrax 3.x

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/scholarspace-hyrax#390]
Align UI and theme of GWSS with other LAI web properties.

**Comment by maxturer** [comment]
Reference of XD mockup [here](https://xd.adobe.com/view/552febc0-e557-404e-8ef1-b1e967eb173a-007c/) (will update automatically if/as needed)

**Comment by kilahimm** [comment]
Resolved in #401
