### ISSUE TITLE
Loading attachments > 100 MB yields error

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace-hyrax#40]
On the file upload tab, the app gives a "Bad Gateway" error (gracefully, not a 404 screen).

**Comment by kerchner** [comment]
For initial deployment, we can opt to exclude ETDs with >100MB attachments (per attachment - total can be > 100MB).  However, we should also define a plan for identifying/inventorying these ETDs and for remediating the limitation and/or finding an alternative way to post these.  Ideas include posting as compressed files (zip, etc.), posting to a static/cloud location and referencing that location, and other possibilities TBD.

**Comment by justinlittman** [comment]
In looking at the existing ETD files, there are over 60 that are greater than 100MB.

```
etdprogram@gwthesis-prod:/var/www/html$ find . -size +100000k | wc -l
61
```

**Comment by kerchner** [comment]
Compressing is probably not a good option.  A test of compressing one ETD only reduced its size by 2%.

**Comment by kerchner** [comment]
I set up a "vanilla" instance of Hyrax that, in development mode, uses fcrepo_wrapper and solr_wrapper.  With this setup, I'm able to attach files > 100MB.

Review of the Hyrax code indicates that the limitation is not with the Hyrax app (default limits appear to be set at 500MB)

**Comment by kerchner** [comment]
This appears to have been caused simply because the root volume on the app server was too close to full.  Ensuring sufficient space on the app server allowed for uploading a file of > 100MB.

However, file characterization is slow for large files, so pressing Save results in a slow return from the page request (a few minutes).  With back-end loading, this isn't as much of an issue, but loading through the UI with inline processing would be a problem.   This would be a point in favor of prioritizing Sidekiq configuration.

Note that it appears that `config/initializers/hyrax.rb` will have a `maxFileSize` setting in Hyrax 2.0.0 -- see https://github.com/samvera/hyrax/blob/v2.0.0.beta2/lib/generators/hyrax/templates/config/hyrax.rb#L30

Closing this issue for now.
