### ISSUE TITLE
ETD ingest rake task should not create null keyword

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace-hyrax#409]
Test to ensure that when no keyword is part of the ETD metadata, that no keyword is created in the GW ScholarSpace ETD work.  Fix if it is creating null keywords.

Note that it is possible the source of the problem is in the (currently Python) ETD loader.

**Comment by dolsysmith** [comment]
I believe that the keyword field is created with a null string in these cases, which is the problem. Where no keywords exist, the keywork field on the ActiveFedora record should be an empty list, not a list of one element that is an empty string.

**Comment by kerchner** [comment]
Closing as we are no longer using this task.  We have not seen this problem (yet) with Bulkrax uploads.  If we do, we can open a new issue.
