### ISSUE TITLE
Styling on Edit User Collection page, under Additional Fields

### ISSUE THREAD

**Issue by dolsysmith** [gwu-libraries/scholarspace-hyrax#451]
The styling appears off in a couple of places

1. There's an extraneous blue border beneath the first Contributor field:
 
<img width="955" alt="Screenshot 2023-11-09 at 11 33 22 AM" src="https://github.com/gwu-libraries/scholarspace-hyrax/assets/22801679/bba1fcc0-e420-4cf1-9835-852449b096d1">

2. The dropdown to select a work type (for the collection as a whole) cuts off at the bottom of the page, and I can't see what's below it. 

<img width="831" alt="Screenshot 2023-11-09 at 11 33 27 AM" src="https://github.com/gwu-libraries/scholarspace-hyrax/assets/22801679/3b615bb7-5011-4edb-b20a-01b957fa2280">

**Comment by maxturer** [comment]
Oh, this is a one-line fix. On it!
