### ISSUE TITLE
Bulkrax styling issue

### ISSUE THREAD

**Issue by dolsysmith** [gwu-libraries/scholarspace-hyrax#452]
After running a Bulkrax import, you can view the results under Dashboard -> Importers, by clicking on the name of the Importer. From there, you can inspect the field parsing for a specific work by clicking on the work identifier and expanding the `Parsed Metadata` modal. (This can be useful for troubleshooting.) 

The resulting text seems to overflow the container and become illegible.

 
<img width="699" alt="Screenshot 2023-11-09 at 11 36 46 AM" src="https://github.com/gwu-libraries/scholarspace-hyrax/assets/22801679/caf25754-c9ce-4e32-879d-3397ad7c429b">

**Comment by maxturer** [comment]
It's likely this is going to be the same fix as #451, but I'll confirm that shortly.

**Comment by dolsysmith** [comment]
CSS magic! Thanks!

**Comment by maxturer** [comment]
Fixed in Pr #453
