### ISSUE TITLE
Update GWSS home page: add orientation/welcome langauge; improve spotlighting

### ISSUE THREAD

**Issue by DaltonAlves** [gwu-libraries/scholarspace-hyrax#473]
During user testing many users were unable to identify the purpose of GWSS when presented with the application’s homepage.

Inclusion of some simple orientation language may address this. In addition, some additional content added to the homepage and adjustment of the current “spotlights” may better prompt the user to interact with GWSS and its content.

In addition, the "spotlight" content was often a point of confusion for users during testing.  Better spotlights might better prompt users to the use-cases of GWSS and facilitate search/retrieval of content.

**Steps/Requirements:**
- Add orientation/welcome language
    - “As the George Washington University’s institutional repository, GW ScholarSpace provides free, public access, broad visibility, and long-term preservation for the research and scholarly works created by GW’s faculty, staff and students, including electronic theses and dissertations (ETDs).”
- Spotlighting
    - Explore GWSS by content type (menu to start faceted search by ‘type of work’)
    - See [Northeastern IR](https://repository.library.northeastern.edu/) for example
    - Content types:
         - ETDs
        - Articles
        - Journals
        - Posters
        - Research Papers
        - Book Reviews
- Keep recent uploads?
- Some access point/spotlight for community collections/administrative sets browse
    - Search list of all community-collections
        - To get user collections like GWUR review
    - search list of all administrative units
    - Example of similar functionality in hyrax repository :https://dl.atla.com/

User Stories:

As a researcher (end-user), I want to browse a list of all of the user collections in GWSS.

As a depositor, I want to quickly understand the value and use of GWSS.

**Comment by DaltonAlves** [comment]
https://docs.google.com/document/d/11HTcgJSD-utvt8WvRy9acWLtB2UONonjfLvMMko5ebs/edit?usp=sharing

**Comment by kerchner** [comment]
Use this link to spotlight all ETDs:

https://scholarspace.library.gwu.edu/catalog?f%5Bhas_model_ssim%5D%5B%5D=GwEtd
