### ISSUE TITLE
Streamline/update current navbar pages

### ISSUE THREAD

**Issue by DaltonAlves** [gwu-libraries/scholarspace-hyrax#475]
**Please hold for further discussion within ScholCom.** 

During user testing, information retrieval/search was difficult in general for almost all users.

- Remove Information for Authors from Navbar
- Put where?

**Comment by kilahimm** [comment]
Nav-bar: About, Contact, Browser Everything.  Possibly move "Share your work" into the nav-bar from the header.  @DaltonAlves will confirm finally decision.

**Comment by DaltonAlves** [comment]
Confirming that we will move "Share Your Work" to navbar. Let keep formatting the same as other navbar items.

**Comment by maxturer** [comment]
In Slack, we chose to remove the "Share Your Work" button for now. It's gone, but here's the Mobile version of the header:
<img width="606" alt="dark blue header" src="https://github.com/gwu-libraries/scholarspace-hyrax/assets/123979081/ef3339fa-d0c0-4522-a22b-42b3067ca973">

I could remove that on mobile, but should we keep it in place for the eventual "Log In" button?
