### ISSUE TITLE
Investigate terms of use

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/scholarspace-hyrax#479]
Do we need both a terms of use and a deposit agreement for the site?  Can we check with our compliance team to see if the GW Terms of Use in the footer is sufficient?

**Comment by kilahimm** [comment]
Pending OGC review.

**Comment by DaltonAlves** [comment]
OGC confirmed that we need to keep the second, GWSS specific, ToS. ScholComm will discuss where to place the GWSS ToS

**Comment by DaltonAlves** [comment]
ToS will be stand alone page (not present on the navbar). Will link GWSS ToS from the about page (see #498) and intermediate deposit page (#478). 

As we begin to flesh out the mediated deposit (#470 ),  we can think through any additional places that the TOS should be presented to the user. Would be appropriate to present again during actual submission process if possible.
