### ISSUE TITLE
Setup CI/CD with Github Actions

### ISSUE THREAD

**Issue by alepbloyd** [gwu-libraries/scholarspace-hyrax#491]
Thinking through next steps on getting this setup working, and here's an outline of what I'm thinking:

- Set up a github workflow to run when a pull request is opened to the `master` branch. This workflow would run two checks:
  - Verify that the docker container builds successfully.
  - Run the RSpec based automated testing suite. 
- If both of those checks pass and someone merges that PR to the `master` branch, it should trigger a workflow to auto-deploy those changes to our `test.scholarspace` instance. 

That would remove the need to manually redeploy to our testing server for regression testing, and lets us try out this system without involving our production server right away.

**Comment by alepbloyd** [comment]
Status as of 2/21/24:

Repository with instructions for setting up Jenkins/NGINX server is here: https://github.com/gwu-libraries/scholarspace-jenkins

Tested CD system with manually triggering redeploy on ScholarSpace test server, which worked. 

I have one open PR related to this (https://github.com/gwu-libraries/scholarspace-hyrax/pull/509) for changing reverting docker volume names and adding passenger restart to redeploy script. After that is reviewed, will work on verifying the Jenkins server is receiving GH webhooks.

**Comment by kerchner** [comment]
@alepbloyd Did #509 complete the work of this issue?
