### ISSUE TITLE
Remove browse_everything mount

### ISSUE THREAD

**Issue by alepbloyd** [gwu-libraries/scholarspace-hyrax#499]
In our `routes.rb` file, we have `mount BrowseEverything::Engine => '/browse'`, but we are not using the `browse_everything` gem and do not have a config file for it set up. 

As a result, instead of a 404 page or redirecting a user to `/catalog` if they visit `/browse`, it results in a rails error page. 

I think we could likely fix this by just removing that line in the routes file.

**Comment by alepbloyd** [comment]
@kilahimm - I'm thinking this issue should be a fairly simple bug fix, and would be a good small PR to queue up for testing the CD pipeline. We don't have it on the board for this current iteration, so wanted to run it by you. 

@maxturer - I know we don't have any links to `/browse`, but I should be able to route it so if a user visits `/browse` for whatever reason, they get redirected to `/catalog`. Do you think that makes sense, or just a normal 404?

**Comment by maxturer** [comment]
I was considering doing this exact thing when setting up the navbar and the route to `/share`, so I'm in favor.
