### ISSUE TITLE
Edits to About, Deposit, and Home pages based on ScholComm and Stakeholder feedback

### ISSUE THREAD

**Issue by DaltonAlves** [gwu-libraries/scholarspace-hyrax#522]
These edits have been suggested based upon the current test server: [https://test.scholarspace.library.gwu.edu/](https://test.scholarspace.library.gwu.edu/)

- [x] Remove "As the George Washington University's institutional repository," from **home page and about page**. 
    - [x] Home page location = paragraph in "intro" class
    - [x] About page location = 1st paragraph in "section-gw-darkblue" 
- [x] Change "h2" headings of **Share Your Work** page to be accordion style items (h2 headings in 'gw-white-content' area only)
- [x] Add additional content to "What do I need to know before I deposit my work?" section of **Share Your Work page**
    - [x] "GW community members affiliated with the GW Law School and the Schools of Public Health, Nursing, & Medicine may utilize the following repositories in addition to GW ScholarSpace: 
    - [x] [Health Sciences Research Commons - Himmelfarb Health Sciences Library](https://hsrc.himmelfarb.gwu.edu/)
[Scholarly Commons - George Washington University Law School](https://scholarship.law.gwu.edu/)"
- [x] On **About page**, swap the h2 headings (and subsequent content): "Why should I submit my works to GW ScholarSpace?" and "What belongs in GW ScholarSpace?"

**Comment by DaltonAlves** [comment]
Some additional edits/comments from scholcomm:
**Home** page
- [ ] Could H1 heading, "GW ScholarSpace" be made smaller?
- [ ] Could the GW Logo in home content area be removed?
- [ ] Swap _Recently Uploaded_ content with _Featured Collections_ content
- [ ] Rename _Recently Uploaded_ to _Recently Submitted_ (the h2 heading)
- [ ] Could a search bar be added to the home content area? 
- [ ] Change the text of the _Browse the Repository_ button in the home content area to _Browse Everything_

**Deposit Your Work** page
- [ ] Could h1 heading, "Share Your Work" be made smaller?
- [ ] Please remove the following text from the deposit info section
    - [ ] The University uses the [ProQuest ETD Administrator](https://www.etdadmin.com/main/home?siteId=55) to facilitate the submission/approval process of GW electronic theses and dissertations. By submitting to the ProQuest ETD Administrator, the final and approved version of your thesis or dissertation will be deposited to [ProQuest's Dissertation and Theses Online Database](http://proxygw.wrlc.org/login?url=http://search.proquest.com/pqdtglobal/advanced?accountid=11243) and the University's institutional repository, [GW ScholarSpace](https://scholarspace.library.gwu.edu/).

**Comment by maxturer** [comment]
I think some header resizes didn't carry over from my convoluted development setup last time. @DaltonAlves Would you be able to confirm that the "about" and "share" h1 headers are still in need of a resize after the most recent update in Pr [526](https://github.com/gwu-libraries/scholarspace-hyrax/pull/526)? Viewable [here on my dev server](http://ec2-34-210-83-142.us-west-2.compute.amazonaws.com/), as a shortcut.

**Comment by DaltonAlves** [comment]
H1 headers look good!

Just realizing that we need to update some additional about page langauge to reflect the new ETD submission outside of LAI. See below for updates:

**About Page**
- [ ] Replace the text under the h3 heading "Submitting Electronic Thesis and Dissertations (ETDs)"
   - [ ] Electronic Thesis and Dissertations (ETDs) must first be submitted via the ProQuest ETD administrator. Please visit [the Office of Graduate and Postdoctoral Affairs' ETD page](https://gradpostdoc.gwu.edu/gw-etds) for more information.<br>
ETDs submitted via this process are automatically ingested into GW ScholarSpace.

**Comment by kerchner** [comment]
@DaltonAlves @maxturer Are there still remaining items from this issue, post-2.1.0?   If so, shall we close this issue and spin the remaining items off as a new issue?
