### ISSUE TITLE
Investigate metatags for date/year of publication (ETDs)

### ISSUE THREAD

**Issue by DaltonAlves** [gwu-libraries/scholarspace-hyrax#539]
Expanding on #343: metatags need to be configured for date/year of publication for inclusion in Google Scholar

From https://scholar.google.com/intl/en/scholar/inclusion.html#indexing (bold is my emphasis):

> The publication date tag, e.g., citation_publication_date or DC.issued, must contain the date of publication, i.e., the date that would normally be cited in references to this paper from other papers. Don't use it for the date of entry into the repository - that should go into citation_online_date instead. Provide full dates in the "2010/5/12" format if available; or a year alone otherwise. **This tag is required for inclusion in Google Scholar.**...
>Keep in mind that, regardless of the meta-tag scheme chosen, you need to provide at least three fields: (1) the title of the article, (2) the full name of at least the first author, and (3) **the year of publication**. Pages that don't provide any one of these three fields will be processed as if they had no meta tags at all. 

As of GWSS 2.1, metatags for ETDs are generated with the below tags:
```
<meta name="citation_institution" value="George Washington University">
<meta name="citation_title" value="Deep Dive: An Investigation into How Divers Use Dynamic Shape Change to Reduce Splash">
<meta name="citation_author" value="Gregorio, Elizabeth">
<meta name="citation_type" value="Dissertation">
<meta name="dc.type" value="Dissertation">
<meta name="citation_keywords" value="Air Cavity">
<meta name="citation_pdf_url" value="http://scholarspace.library.gwu.edu/downloads/n583xv64m">`
```

Examples of implementation of date/year of publication metatags:

From Emory's ETD repo:
```
<meta name="citation_date" value="10 January 2024">
```

Example schema provided by google:
```
<meta name="citation_publication_date" content="1996/05/17">
```

**Comment by kerchner** [comment]
Current ETD `date_created` values on production are all (100%) of the form YYYY.   Based on this, we can, for now, populate `citation_publication_date` with `date_created` from the GwETD.  If in the future we encounter ETDs with a different date format that requires standardizing to one of the formats specified by Google Scholar (YYYY or YYYY/MM/DD) then we can enhance at that point.
