### ISSUE TITLE
Standardize development/seeding data set

### ISSUE THREAD

**Issue by alepbloyd** [gwu-libraries/scholarspace-hyrax#557]
Standardize the development/seeded data set, goal of making the development environment more consistent for everyone. 

The data should include:
- Users
  - Admin
  - Content Admin
  - Authenticated (GW, non-admin)
- Works
  - Visibility options 
    - Public
    - Private
    - Authenticated (visible to logged in GW users)
  - With attachments
    - PDFs
    - Images (JPEG?)
    - Any other file types that we accept for deposit? I believe this is on the site somewhere. 
  - Other considerations
    - Range of 'created at' times for works. 
- Collections with works added to them
- Anything else?

We currently have this functionality spread between a few rake tasks and a seeds file. I think either option is fine, as long as we just pick which one to stick with and combine this functionality into. Because the `prep_new_prod` task already handles creating a new empty version, I'm thinking we could go with the seeds file option for this - open to other preferences though.

**Comment by dolsysmith** [comment]
I'd suggest creating works in different admin sets: GwEtd, GwWork.
