### ISSUE TITLE
Update font on homepage

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/scholarspace-hyrax#565]
Adjust font on homepage per stakeholder feedback about the "hero section".

**Comment by maxturer** [comment]
Here's a selection of GW-legal or dubiously-GW-legal homepage H1 options.

Legal, GW Liberated (I don't advise using this):
![gw-liberated](https://github.com/user-attachments/assets/3a3962f7-a473-4fde-9a79-d34f0ca6675c)

Sort of legal, Hoefler Italic:
![hoefler-italic](https://github.com/user-attachments/assets/68df892e-da10-4afd-a8e9-009b2411d869)

Vaguely Legal, Hoefler Swash:
![hoefler-swash](https://github.com/user-attachments/assets/4e26b99a-5295-4db8-b7e3-ec6d2b9bd2ae)

Combinations that I think are nice (Gibson + Hoefler Swash):
![gibson-and-hoefler-swash](https://github.com/user-attachments/assets/9b42e2b2-ddc7-4592-804f-97027ee5f079)
![gibson-and-hoefler-swash-buff](https://github.com/user-attachments/assets/8325848f-004b-4fd9-9cf4-2c8c6c3ece87)

**Comment by labarba** [comment]
If I may contribute an opinion here, purely from a graphic design perspective, none of these options look clean. 

- Lack of "air" — any typographical elements need sufficient whitespace around them. If your _really_ feel the need to add a large "GW Scholar Space" header, give it room so the page doesn't look crowded.
- Do you _really need_ to add that header? The name of the site is on the URL and next to the GW monogram logo. The important thing is for visitors to know what this is: the university's institutional repository, which you have added under the header. The text below explains what ScholarSpace is. 
- The swash options should not be used for a title heading, much less combined with another font (sans-serif "GW")

And again I'd like to repeat that you don't need another GW logo, as the logo is both in the header and the footer. Moreover the blue-background logo (white fonts) is not used on a white page.

Try deleting the h1 title altogether and deleting the blue logo, and let it breathe better.

**Comment by labarba** [comment]
For visual comparison, and to illustrate what I mean by "clean," here is the mockup I shared on Slack a few weeks ago:

![Screenshot 2024-06-19 at 6 31 38 PM](https://github.com/user-attachments/assets/b4ae7184-885f-4eda-a472-5daf99810f7f)

**Comment by labarba** [comment]
In most GW webpages, the GW Liberated typeface is used for slogan-style marketing text, and the swash is used for brief complementary marketing copy—often combined with a hero image on top. 

So another option for your landing page could have that style, as shown in the mockup below.

<img width="1157" alt="Screenshot 2024-08-29 at 5 25 14 PM" src="https://github.com/user-attachments/assets/75551d6d-b590-4a16-bc10-e32ccec3a9ab">

Below this can come other sections with links to browse by category, etc.
