### ISSUE TITLE
Help page browse link 

### ISSUE THREAD

**Issue by reliztrent** [gwu-libraries/scholarspace-hyrax#94]
"Browse" link at top of https://scholarspace-etds.library.gwu.edu/help goes to https://scholarspace.library.gwu.edu/help#browse instead of relative link to #browse

**Comment by kerchner** [comment]
Thanks @reliztrent .  Fixed on the live site and also at https://gist.github.com/kerchner/98e0809ef8b023450911925c68dce4f6
