### ISSUE TITLE
Deployment is tedious, try again to dockerize

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace-hyrax#99]
This can also improve reproduceability of deployments.

Partial solutions may be useful as well, for example a container just for the rails app, and/or a container just for solr

**Comment by dolsysmith** [comment]
### Working so far

#### postgres container: hyrax
   - Uses Docker volume for persistence
   - Migration notes:
     - Cleanest way: use `pg_dump` to create a backup of the database outside the container, then
     - `docker cp backup.sql db-container:/tmp` to copy the dump into the running container
     - `docker exec -it db-container /bin/bash`
     - (inside the container) `psql -U scholarspace -d gwss-prod < /tmp/backup.sql` to restore the backup

#### postgres container-fcrepo
   - Docker volume for persistence
   - Connect to Fedora via Docker network

#### fedora container
   - `ghcr.io/samvera/fcrepo4:4.7.5` seems to work
   - pass `$JAVA_OPTIONS` in docker-compose `environment` section, including fcrepo DB username & password
   - Map to external volume (bind mount)
   - Dockerfile (for reference): https://github.com/samvera-labs/docker-fcrepo

#### solr container
   - `Dockerfile-solr`:
   		- Builds from `6.4.2-alpine` (https://github.com/docker-solr/docker-solr/blob/master/6.6)
   		- ** Note that the instructions for the older Solr Docker images are different from the latest
   		- Includes `solr/config` from the GWSS repo 
   		- Runs init script as entrypoint
   - Init script:
   		- If the `scholarspace` core does not exist, create it
	        - Apply the schema from the ScholarSpace repo
		- Otherwise, use the existing core
  - Mapped volume (bind mount): /var/solr/data:/opt/solr/server/solr/mycores
  - `chown -R 8983:8938 /var/solr/data` before starting container (`8983` is the `solr` UID/GID inside the container)


#### In progress

- Docker image for Rails app/Passenger/Apache

### To test

1. Complete set up of new instance
2. Migrate existing instance
    - Fedora binaries -> container (via mapped volume)
    - Fedora postgres database -> container (via backup/restore)
      - May need to use a different postgres image
    - Confirm Hyrax postgres database migration

**Comment by kilahimm** [comment]
Resolved in #401
